### ISSUE TITLE
BackendService NullPointerException

### ISSUE THREAD

**Issue by xuefer** [microg/AppleWifiNlpBackend#17]
```
01-28 16:46:18.250 12257 28801 W AppleNlpBackendService: java.lang.NullPointerException
01-28 16:46:18.250 12257 28801 W AppleNlpBackendService:  at org.microg.nlp.backend.apple.BackendService$1.run(BackendService.java:57)
01-28 16:46:18.250 12257 28801 W AppleNlpBackendService:  at java.lang.Thread.run(Thread.java:841)
01-28 16:46:18.250 12257 28801 W dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x4160ed58)
01-28 16:46:18.251 12257 28801 E AndroidRuntime: FATAL EXCEPTION: Thread-1751
01-28 16:46:18.251 12257 28801 E AndroidRuntime: Process: org.microg.nlp.backend.apple, PID: 12257
01-28 16:46:18.251 12257 28801 E AndroidRuntime: java.lang.NullPointerException
01-28 16:46:18.251 12257 28801 E AndroidRuntime:  at org.microg.nlp.backend.apple.BackendService$1.run(BackendService.java:79)
01-28 16:46:18.251 12257 28801 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:841)
```

I'm not sure how to reproduce, i just leave it on for some time. by checking the code it looks like onWiFIChange comes before onOpen which is the only case leads to "database == NULL"

**Comment by ale5000-git** [comment]
Have you tried the latest version?
